[package]
name = "vestinglib"
version = "0.1.3"
edition = "2021"
description = "A library used to compute the vesting math needed for a Solana program"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
